
export PYTHIA8=/Applications/pythia8
export PYTHIA8_HOME=$PYTHIA8
export PYTHIA8__HOME=$PYTHIA8_HOME  
export LD_LIBRARY_PATH=$PYTHIA8__HOME/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Qt-5.12.11/lib
export CMAKE_PREFIX_PATH=/usr/local/Qt-5.12.11
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Applications/Qt5.12.10/5.12.10/clang_64/lib

export G4RHADRONS=/Users/jkiesele/work/dmbottle/G4Rhadrons_with_Regge_model
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$G4RHADRONS

export G4DATAINSTALL=/usr/local/share/Geant4-10.6.2
export G4LEVELGAMMADATA=$G4DATAINSTALL/data/PhotonEvaporation5.5
export G4NEUTRONXSDATA=$G4DATAINSTALL/data/G4NEUTRONXS1.4
export G4LEDATA=$G4DATAINSTALL/data/G4EMLOW7.9.1
export G4SAIDXSDATA=$G4DATAINSTALL/data/G4SAIDDATA2.0
export G4RADIOACTIVEDATA=$G4DATAINSTALL/data/RadioactiveDecay5.4
export G4NEUTRONHPDATA=$G4DATAINSTALL/data/G4NDL4.6
export G4ENSDFSTATEDATA=$G4DATAINSTALL/data/G4ENSDFSTATE2.2
export G4PARTICLEXSDATA=$G4DATAINSTALL/data/G4PARTICLEXS2.1
